[package]
name = "abacus"
version = "0.1.0"
edition = "2021"
authors = ["Michael Pyle"]
description = "Analytic Processor"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
datafusion = "20.0.0"
petgraph = "0.6.3"
serde = { version = "1.0.156", features = ["derive"] }
serde_json = "1.0.94"
tokio = { version = "1.26.0", features = ["full"] }

[profile.release]
lto = "thin"
codegen-units = 1
incremental = true
